# Site settings
author: Yukiko Ikeda
title: Software Engineering Course
header-img: img/home-bg.png
email: applelele@gmail.com
copyright_name: Yukiko Ikeda
description: > # this means to ignore newlines until "baseurl:"
  What I have learnt
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  applelele

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
